### PR TITLE
Use GetFlushState to check Flush progress

### LINKED ISSUE #234: [Bug]: Flush check method is out of date
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Sync `Flush` uses GetPersistentSegments to check Flush State

### Expected Behavior

Use new added api `GetFlushState`

### Steps To Reproduce

```markdown
Run e2e examples
```

### Environment

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by congqixia**
Update proto to latest
Use `GetFlushState` to check flush progress in sync call

Fix #234 

/kind bug

Signed-off-by: Congqi Xia <congqi.xia@zilliz.com>

### CODE REVIEW

File: client/client_grpc_data.go [hunk 1]
```diff
@@ -141,27 +141,21 @@ func (c *grpcClient) Flush(ctx context.Context, collName string, async bool) err
 	}
 	if !async {
 		segmentIDs, has := resp.GetCollSegIDs()[collName]
-		if has {
+		ids := segmentIDs.GetData()
+		if has && len(ids) > 0 {
 			waitingSet := make(map[int64]struct{})
 			for _, segmentID := range segmentIDs.GetData() {
 				waitingSet[segmentID] = struct{}{}
 			}
```
Comment (sunby) [inline client/client_grpc_data.go:149]: Do we need `waitingSet` anymore?

Comment (congqixia) [reply client/client_grpc_data.go]: Fixed
